package org.nova.html.localization;

import org.nova.html.ext.Locale_ISO_639_1;

//public enum LanguageCode
//{
//    Abkhazian("ab"),
//    Afar("aa"),
//    Afrikaans("af"),
//    Akan("ak"),
//    Albanian("sq"),
//    Amharic("am"),
//    Arabic("ar"),
//    Aragonese("an"),
//    Armenian("hy"),
//    Assamese("as"),
//    Avaric("av"),
//    Avestan("ae"),
//    Aymara("ay"),
//    Azerbaijani("az"),
//    Bambara("bm"),
//    Bashkir("ba"),
//    Basque("eu"),
//    Belarusian("be"),
//    Bengali("bn"), 
////    Bhutani("dz"),
//    Bihari("bh"),
//    Bislama("bi"),
//    Breton("br"),
//    Bulgarian("bg"),
//    Burmese("my"),
////    Belarussian("be"),
////    Cambodian("km"),
//    Catalan("ca"),
//    Chamorro("ch"),
//    Chechen("ce"),
////    Cherokee    -
//  //  Chewa   -
//    Chinese("zh"),
////    Chinese (Simplified)    zh-Hans
////    Chinese (Traditional)   zh-Hant
//    Chuvash("cv"),
//    Cornish("kw"),
//
//    Corsican("co"),
//    Cree("cr"),
//    Croatian("hr"),
//    Czech("cs"),
//    Danish("da"),
//    Divehi("dv"),
//    Dhivehi("dv"),
//    Maldivian("dv"),
//    Dutch("nl"),
////    Edo -
//    English("en"),
//    Esperanto("eo"),
//    Estonian("et"),
//    Ewe("ee"),
//    Faeroese("fo"),
//    Farsi("fa"),  //??
//    Fijian("fj"),
//    Finnish("fi"),
////    Flemish -
//    French("fr"),
//    Fula("fr"),
//    Fulah("fr"),
//    Pulaar("fr"),
//    Pular("fr"),
//    
////    Frisian("fy"),
////    Fulfulde    -
//    Galician("gl"),
////    Gaelic (Scottish)   gd
////    Gaelic (Manx)   gv
//  ///???  Georgian("ka"),
//    German("de"),
//    Greek("el"),
//    Greenlandic("kl"),
//    Guarani("gn"),
//    Gujarati("gu"),
////    Haitian Creole  ht
//    Hausa("ha"),
////    Hawaiian    -
//    Hebrew("he, iw"),
//    Hindi("hi"),
//    Hungarian("hu"),
////    Ibibio  -
//    Icelandic("is"),
//    Ido("io"),
////    Igbo    -
//    Indonesian("id, in"),
//    Interlingua("ia"),
//    Interlingue("ie"),
//    Inuktitut("iu"),
//    Inupiak("ik"),
//    Irish("ga"),
//    Italian("it"),
//    Japanese("ja"),
//    Javanese("jv"),
//    Kannada("kn"),
////    Kanuri  -
//    Kashmiri("ks"),
//    Kazakh("kk"),
////    Kinyarwanda (Rwanda)("rw"),
//    Kirghiz("ky"),
////    Kirundi (Rundi) rn
////    Konkani -
//    Korean("ko"),
//    Kurdish("ku"),
//    Laothian("lo"),
//    Latin("la"),
////    Latvian (Lettish)   lv
// //   Limburgish (Limburger)  li
//    Lingala("ln"),
//    Lithuanian("lt"),
//    Macedonian("mk"),
//    Malagasy("mg"),
//    Malay("ms"),
//    Malayalam("ml"),
//    Maltese("mt"),
//    Maori("mi"),
//    Marathi("mr"),
//    Mongolian("mn"),
//    Nauru("na"),
//    Nepali("ne"),
//    Norwegian("no"),
//    Occitan("oc"),
//    Oriya("or"),
////    Oromo (Afaan Oromo) om
////    Papiamentu  -
//  //  Pashto (Pushto)("ps
//    Polish("pl"),
//    Portuguese("pt"),
//    Punjabi("pa"),
//    Quechua("qu"),
////    Rhaeto-Romance("rm
//    Romanian("ro"),
//    Russian("ru"),
////    Sami (Lappish)  -
//    Samoan("sm"),
//    Sangro("sg"),
//    Sanskrit("sa"),
//    Serbian("sr"),
////    Serbo-Croatian("sh"),
//    Sesotho("st"),
//    Setswana("tn"),
//    Shona("sn"),
////    Sichuan Yi("ii"),
//            
//    Sindhi("sd"),
//    Sinhalese("si"),
//    Siswati("ss"),
//    Slovak("sk"),
//    Slovenian("sl"),
//    Somali("so"),
//    Spanish("es"),
//    Sundanese("su"),
////    Swahili (Kiswahili)("sw"),
//    Swedish("sv"),
////    Syriac  -
//    Tagalog("tl"),
//    Tajik("tg"),
////    Tamazight   -
//    Tamil("ta"),
//    Tatar("tt"),
//    Telugu("te"),
//    Thai("th"),
////    Tibetan("
//    Tigrinya("ti"),
//    Tonga("to"),
//    Tsonga("ts"),
//    Turkish("tr"),
//    Turkmen("tk"),
//    Twi("tw"),
//    Uighur("ug"),
//    Ukrainian("uk"),
//    Urdu("ur"),
//    Uzbek("uz"),
////    Venda   -
//    Vietnamese("vi"),
////    Volap�k("vo"),
//    Wallon("wa"),
//    Welsh("cy"),
//    Wolof("wo"),
//    Xhosa("xh"),
////    Yi  -
//    Yiddish("yi , ji"),
//    Yoruba("yo"),
//    Zulu("zu"),
//    ;
//    
//    private String value;
//
//    LanguageCode(String value)
//    {
//        this.value = value;
//    }
//
//    public String getValue()
//    {
//        return this.value;
//    }
//    
//}

public enum LanguageCode
{
    Abkhazian(new Locale_ISO_639_1("Abkhazian","ab")),
    Afar(new Locale_ISO_639_1("Afar","aa")),
    Afrikaans(new Locale_ISO_639_1("Afrikaans","af")),
    Akan(new Locale_ISO_639_1("Akan","ak")),
    Albanian(new Locale_ISO_639_1("Albanian","sq")),
    Amharic(new Locale_ISO_639_1("Amharic","am")),
    Arabic(new Locale_ISO_639_1("Arabic","ar")),
    Aragonese(new Locale_ISO_639_1("Aragonese","an")),
    Armenian(new Locale_ISO_639_1("Armenian","hy")),
    Assamese(new Locale_ISO_639_1("Assamese","as")),
    Avaric(new Locale_ISO_639_1("Avaric","av")),
    Avestan(new Locale_ISO_639_1("Avestan","ae")),
    Aymara(new Locale_ISO_639_1("Aymara","ay")),
    Azerbaijani(new Locale_ISO_639_1("Azerbaijani","az")),
    Bambara(new Locale_ISO_639_1("Bambara","bm")),
    Bashkir(new Locale_ISO_639_1("Bashkir","ba")),
    Basque(new Locale_ISO_639_1("Basque","eu")),
    Belarusian(new Locale_ISO_639_1("Belarusian","be")),
    Bengali(new Locale_ISO_639_1("Bengali (Bangla)","bn")),
    
    Bihari(new Locale_ISO_639_1("Bihari","bh")),
    Bislama(new Locale_ISO_639_1("Bislama","bi")),
    Bosnian(new Locale_ISO_639_1("Bosnian","bs")),
    Breton(new Locale_ISO_639_1("Breton","br")),
    Bulgarian(new Locale_ISO_639_1("Bulgarian","bg")),
    Burmese(new Locale_ISO_639_1("Burmese","my")),
    Catalan(new Locale_ISO_639_1("Catalan","ca")),
    Chamorro(new Locale_ISO_639_1("Chamorro","ch")),
    Chechen(new Locale_ISO_639_1("Chechen","ce")),
    Chichewa(new Locale_ISO_639_1("Chichewa","ny")),
    Chewa(new Locale_ISO_639_1("Chewa","ny")),
    Nyanja(new Locale_ISO_639_1("Nyanja","ny")),
    
    Chinese(new Locale_ISO_639_1("Chinese","zh")),
    Chinese_Simplified(new Locale_ISO_639_1("Chinese (Simplified)","zh-Hans",null,"zh")),
    Chinese_Traditional(new Locale_ISO_639_1("Chinese (Traditional)","zh-Hant",null,"zh")),
    Chuvash(new Locale_ISO_639_1("Chuvash","cv")),
    Cornish(new Locale_ISO_639_1("Cornish","kw")),
    Corsican(new Locale_ISO_639_1("Corsican","co")),
    Cree(new Locale_ISO_639_1("Cree","cr")),
    Croatian(new Locale_ISO_639_1("Croatian","hr")),
    Czech(new Locale_ISO_639_1("Czech","cs")),
    Danish(new Locale_ISO_639_1("Danish","da")),
    Divehi(new Locale_ISO_639_1("Divehi","da")),
    Dhivehi(new Locale_ISO_639_1("Dhivehi","da")),
    Maldivian(new Locale_ISO_639_1("Maldivian","da")),
    Dutch(new Locale_ISO_639_1("Dutch","nl")),
    Dzongkha(new Locale_ISO_639_1("Dzongkha","dz")),
    English(new Locale_ISO_639_1("English","en")),
    Esperanto(new Locale_ISO_639_1("Esperanto","eo")),
    Estonian(new Locale_ISO_639_1("Estonian","et")),
    Ewe(new Locale_ISO_639_1("Ewe","ee")),
    Faroese(new Locale_ISO_639_1("Faroese","fo")),
    Fijian(new Locale_ISO_639_1("Fijian","fj")),
    Finnish(new Locale_ISO_639_1("Finnish","fi")),
    French(new Locale_ISO_639_1("French","fr")),
    Fula(new Locale_ISO_639_1("Fula","ff")),
    Fulah(new Locale_ISO_639_1("Fulah","ff")),
    Pulaar(new Locale_ISO_639_1("Pulaar","ff")),
    Pular(new Locale_ISO_639_1("Pular","ff")),
    Galician(new Locale_ISO_639_1("Galician","gl")),
    Gaelic_Scottish(new Locale_ISO_639_1("Gaelic (Scottish)","gd")),
    Gaelic_Manx(new Locale_ISO_639_1("Gaelic (Manx)","gv")),
    Georgian(new Locale_ISO_639_1("Georgian","ka")),
    German(new Locale_ISO_639_1("German","de")),
    Greek(new Locale_ISO_639_1("Greek","el")),
    Greenlandic(new Locale_ISO_639_1("Greenlandic","kl")),
    Guarani(new Locale_ISO_639_1("Guarani","gn")),
    Gujarati(new Locale_ISO_639_1("Gujarati","gu")),
    Haitian_Creole(new Locale_ISO_639_1("Haitian Creole","ht")),
    Hausa(new Locale_ISO_639_1("Hausa","ha")),
    Hebrew(new Locale_ISO_639_1("Hebrew","he")),
    Herero(new Locale_ISO_639_1("Herero","hz")),
    Hindi(new Locale_ISO_639_1("Hindi","hi")),
    Hiri_Motu(new Locale_ISO_639_1("Hiri Motu","ho")),
    Hungarian(new Locale_ISO_639_1("Hungarian","hu")),
    Icelandic(new Locale_ISO_639_1("Icelandic","is")),
    Ido(new Locale_ISO_639_1("Ido","io")),
    Igbo(new Locale_ISO_639_1("Igbo","ig")),
    Indonesian(new Locale_ISO_639_1("Indonesian","id","in","id")),
    Interlingua(new Locale_ISO_639_1("Interlingua","ia")),
    Interlingue(new Locale_ISO_639_1("Interlingue","ie")),
    Inuktitut(new Locale_ISO_639_1("Inuktitut","iu")),
    Inupiak(new Locale_ISO_639_1("Inupiak","ik")),
    Irish(new Locale_ISO_639_1("Irish","ga")),
    Italian(new Locale_ISO_639_1("Italian","it")),
    Japanese(new Locale_ISO_639_1("Japanese","ja")),
    Javanese(new Locale_ISO_639_1("Javanese","jv")),
    Kalaallisut(new Locale_ISO_639_1("Kalaallisut","kl")),
    Kannada(new Locale_ISO_639_1("Kannada","kn")),
    Kanuri(new Locale_ISO_639_1("Kanuri","kr")),
    Kashmiri(new Locale_ISO_639_1("Kashmiri","ks")),
    Kazakh(new Locale_ISO_639_1("Kazakh","kk")),
    Khmer(new Locale_ISO_639_1("Khmer","km")),
    Kikuyu(new Locale_ISO_639_1("Kikuyu","ki")),
    Kinyarwanda_Rwanda(new Locale_ISO_639_1("Kinyarwanda (Rwanda)","rw")),
    Kirundi(new Locale_ISO_639_1("Kirundi","rn")),
    Kyrgyz(new Locale_ISO_639_1("Kyrgyz","ky")),
    Komi(new Locale_ISO_639_1("Komi","kv")),
    Kongo(new Locale_ISO_639_1("Kongo","kg")),
    Korean(new Locale_ISO_639_1("Korean","ko")),
    Kurdish(new Locale_ISO_639_1("Kurdish","ku")),
    Kwanyama(new Locale_ISO_639_1("Kwanyama","kj")),
    Lao(new Locale_ISO_639_1("Lao","lo")),
    Latin(new Locale_ISO_639_1("Latin","la")),
    Latvian_Lettish(new Locale_ISO_639_1("Latvian (Lettish)","lv")),
    Limburgish_Limburger(new Locale_ISO_639_1("Limburgish (Limburger)","li")),
    Lingala(new Locale_ISO_639_1("Lingala","ln")),
    Lithuanian(new Locale_ISO_639_1("Lithuanian","lt")),
    Luga_Katanga(new Locale_ISO_639_1("Luga-Katanga","lu")),
    Luganda_Ganda(new Locale_ISO_639_1("Luganda Ganda","lg")),
    Luxembourgish(new Locale_ISO_639_1("Luxembourgish","lb")),
    Manx(new Locale_ISO_639_1("Manx","gv")),
    Macedonian(new Locale_ISO_639_1("Macedonian","mk")),
    Malagasy(new Locale_ISO_639_1("Malagasy","mg")),
    Malay(new Locale_ISO_639_1("Malay","ms")),
    Malayalam(new Locale_ISO_639_1("Malayalam","ml")),
    Maltese(new Locale_ISO_639_1("Maltese","mt")),
    Maori(new Locale_ISO_639_1("Maori","mi")),
    Marathi(new Locale_ISO_639_1("Marathi","mr")),
    Marshallese(new Locale_ISO_639_1("Marshallese","mh")),
    Moldavian(new Locale_ISO_639_1("Moldavian","mo")),
    Mongolian(new Locale_ISO_639_1("Mongolian","mn")),
    Nauru(new Locale_ISO_639_1("Nauru","na")),
    Navajo(new Locale_ISO_639_1("Navajo","nv")),
    Ndonga(new Locale_ISO_639_1("Ndonga","ng")),
    Northern_Ndebele(new Locale_ISO_639_1("Northern Ndebele","nd")),
    Nepali(new Locale_ISO_639_1("Nepali","ne")),
    Norwegian(new Locale_ISO_639_1("Norwegian","no")),
    Norwegian_bokmål(new Locale_ISO_639_1("Norwegian bokmål","nb")),
    Norwegian_nynorsk(new Locale_ISO_639_1("Norwegian nynorsk","nn")),
    Nuosu(new Locale_ISO_639_1("Nuosu","ii")),
    Occitan(new Locale_ISO_639_1("Occitan","oc")),
    Ojibwe(new Locale_ISO_639_1("Ojibwe","oj")),
    Old_Church(new Locale_ISO_639_1("Old Church","cu")),
    Old_Bulgarian(new Locale_ISO_639_1("Old Bulgarian","cu")),
    Oriya(new Locale_ISO_639_1("Oriya","or")),
    Oromo_Afaan_Oromo(new Locale_ISO_639_1("Oromo (Afaan Oromo)","om")),
    Ossetian(new Locale_ISO_639_1("Ossetian","os")),
    Pāli(new Locale_ISO_639_1("Pāli","pi")),
    Pashto(new Locale_ISO_639_1("Pushto","ps")),
    Pushto(new Locale_ISO_639_1("Pushto","ps")),
    Persian_Farsi(new Locale_ISO_639_1("Persian (Farsi)","fa")),
    Polish(new Locale_ISO_639_1("Polish","pl")),
    Portuguese(new Locale_ISO_639_1("Portuguese","pt")),
    Punjabi_Eastern(new Locale_ISO_639_1("Punjabi (Eastern)","pa")),
    Quechua(new Locale_ISO_639_1("Quechua","qu")),
    Romansh(new Locale_ISO_639_1("Romansh","rm")),
    Romanian(new Locale_ISO_639_1("Romanian","ro")),
    Russian(new Locale_ISO_639_1("Russian","ru")),
    Sami(new Locale_ISO_639_1("Sami","se")),
    Samoan(new Locale_ISO_639_1("Samoan","sm")),
    Sango(new Locale_ISO_639_1("Sango","sg")),
    Sanskrit(new Locale_ISO_639_1("Sanskrit","sa")),
    Serbian(new Locale_ISO_639_1("Serbian","sr")),
    Serbo_Croatian(new Locale_ISO_639_1("Serbo-Croatian","sh")),
    Sesotho(new Locale_ISO_639_1("Sesotho","st")),
    Setswana(new Locale_ISO_639_1("Setswana","tn")),
    Shona(new Locale_ISO_639_1("Shona","sn")),
    Sichuan_Yi(new Locale_ISO_639_1("Sichuan Yi","ii")),
    Sindhi(new Locale_ISO_639_1("Sindhi","sd")),
    Sinhalese(new Locale_ISO_639_1("Sinhalese","si")),
    Siswati(new Locale_ISO_639_1("Siswati","ss")),
    Slovak(new Locale_ISO_639_1("Slovak","sk")),
    Slovenian(new Locale_ISO_639_1("Slovenian","sl")),
    Somali(new Locale_ISO_639_1("Somali","so")),
    Southern_Ndebele(new Locale_ISO_639_1("Southern Ndebele","nr")),
    Spanish(new Locale_ISO_639_1("Spanish","es")),
    Sundanese(new Locale_ISO_639_1("Sundanese","su")),
    Swahili_Kiswahili(new Locale_ISO_639_1("Swahili (Kiswahili)","sw")),
    Swati(new Locale_ISO_639_1("Swati","ss")),
    Swedish(new Locale_ISO_639_1("Swedish","sv")),
    Tagalog(new Locale_ISO_639_1("Tagalog","tl")),
    Tahitian(new Locale_ISO_639_1("Tahitian","ty")),
    Tajik(new Locale_ISO_639_1("Tajik","tg")),
    Tamil(new Locale_ISO_639_1("Tamil","ta")),
    Tatar(new Locale_ISO_639_1("Tatar","tt")),
    Telugu(new Locale_ISO_639_1("Telugu","te")),
    Thai(new Locale_ISO_639_1("Thai","th")),
    Tibetan(new Locale_ISO_639_1("Tibetan","bo")),
    Tigrinya(new Locale_ISO_639_1("Tigrinya","ti")),
    Tonga(new Locale_ISO_639_1("Tonga","to")),
    Tsonga(new Locale_ISO_639_1("Tsonga","ts")),
    Turkish(new Locale_ISO_639_1("Turkish","tr")),
    Turkmen(new Locale_ISO_639_1("Turkmen","tk")),
    Twi(new Locale_ISO_639_1("Twi","tw")),
    Uyghur(new Locale_ISO_639_1("Uyghur","ug")),
    Ukrainian(new Locale_ISO_639_1("Ukrainian","uk")),
    Urdu(new Locale_ISO_639_1("Urdu","ur")),
    Uzbek(new Locale_ISO_639_1("Uzbek","uz")),
    Venda(new Locale_ISO_639_1("Venda","ve")),
    Vietnamese(new Locale_ISO_639_1("Vietnamese","vi")),
    Volapük(new Locale_ISO_639_1("Volapük","vo")),
    Wallon(new Locale_ISO_639_1("Wallon","wa")),
    Welsh(new Locale_ISO_639_1("Welsh","cy")),
    Wolof(new Locale_ISO_639_1("Wolof","wo")),
    Western_Frisian(new Locale_ISO_639_1("Western Frisian","fy")),
    Xhosa(new Locale_ISO_639_1("Xhosa","xh")),
    Yiddish(new Locale_ISO_639_1("Yiddish","yi","ji","yi")),
    Yoruba(new Locale_ISO_639_1("Yoruba","yo")),
    Zhuang(new Locale_ISO_639_1("Chuang","za")),
    Chuang(new Locale_ISO_639_1("Chuang","za")),
    Zulu(new Locale_ISO_639_1("Zulu","zu")),
    ;
    
    private Locale_ISO_639_1 value;

    LanguageCode(Locale_ISO_639_1 value)
    {
        this.value = value;
    }

    public Locale_ISO_639_1 getValue()
    {
        return this.value;
    }
    
//    public static LanguageCode fromValue(short value)
//    {
//        for (LanguageCode type : LanguageCode.values())
//        {
//            if (type.name().equals(anObject) == value)
//            {
//                return type;
//            }
//        }
//        return null;
//    }

}
