package org.nova.logsearch;

public enum Code
{
    ADD_INTEGER_INTEGER,
    ADD_INTEGER_NUMBER,
    ADD_INTEGER_STRING,

    ADD_NUMBER_INTEGER,
    ADD_NUMBER_NUMBER,
    ADD_NUMBER_STRING,

    ADD_STRING_INTEGER,
    ADD_STRING_NUMBER,
    ADD_STRING_STRING,
    
    SUBTRACT_INTEGER_INTEGER,
    SUBTRACT_INTEGER_NUMBER,
    
    SUBTRACT_NUMBER_INTEGER,
    SUBTRACT_NUMBER_NUMBER,
    
    MULTIPLY_INTEGER_INTEGER,
    MULTIPLY_INTEGER_NUMBER,
    MULTIPLY_NUMBER_INTEGER,
    MULTIPLY_NUMBER_NUMBER,
    
    DIVIDE_INTEGER_INTEGER,
    DIVIDE_INTEGER_NUMBER,
    DIVIDE_NUMBER_INTEGER,
    DIVIDE_NUMBER_NUMBER,
    
    EQUAL_INTEGER_INTEGER,
    EQUAL_INTEGER_NUMBER,
    EQUAL_NUMBER_INTEGER,
    EQUAL_NUMBER_NUMBER,
    EQUAL_STRING_STRING,
    EQUAL_BOOLEAN_BOOLEAN,
    
    GREATER_INTEGER_INTEGER,
    GREATER_INTEGER_NUMBER,
    GREATER_NUMBER_INTEGER,
    GREATER_NUMBER_NUMBER,
    GREATER_STRING_STRING,
            
    LESS_INTEGER_INTEGER,
    LESS_INTEGER_NUMBER,
    LESS_NUMBER_INTEGER,
    LESS_NUMBER_NUMBER,
    LESS_STRING_STRING,
    
    GREATER_EQUAL_INTEGER_INTEGER,
    GREATER_EQUAL_INTEGER_NUMBER,
    GREATER_EQUAL_NUMBER_INTEGER,
    GREATER_EQUAL_NUMBER_NUMBER,
    GREATER_EQUAL_STRING_STRING,
    
    LESS_EQUAL_INTEGER_INTEGER,
    LESS_EQUAL_INTEGER_NUMBER,
    LESS_EQUAL_NUMBER_INTEGER,
    LESS_EQUAL_NUMBER_NUMBER,
    LESS_EQUAL_STRING_STRING,
    
    NOT_EQUAL_INTEGER_INTEGER,
    NOT_EQUAL_INTEGER_NUMBER,
    NOT_EQUAL_NUMBER_INTEGER,
    NOT_EQUAL_NUMBER_NUMBER,
    NOT_EQUAL_STRING_STRING,
    NOT_EQUAL_BOOLEAN_BOOLEAN,
    
    AND,
    OR,
    NOT,
    CONTAINS,
    
    PUSH_NUMBER,
    PUSH_LOG_LEVEL,
    PUSH_CATEGORY,
    PUSH_CREATED,
    PUSH_MESSAGE,
    PUSH_EXCEPTION,
    PUSH_STACK_TRACE,
    PUSH_TRACE_NUMBER,
    PUSH_TRACE_CREATED,
    PUSH_TRACE_CATEGORY,
    PUSH_DURATION,
    PUSH_WAIT,
    PUSH_FROM_LINK,
    PUSH_TO_LINK,
    PUSH_TRACE_EXCEPTION,
    PUSH_TRACE_STACK_TRACE,
    
    PUSH_CONSTANT,
    PUSH_ITEM_KEY
}